export  const Menu= [
    {
        id:1,
        image:"images/B1.jpg",
        name:"Breakfast1",
        category:"breakfast",
        price:"",
        description:""
    },
    {
        id:2,
        image:"images/B2.jpg",
        name:"Breakfast2",
        category:"breakfast",
        price:"",
        description:""
    },
    {
        id:3,
        image:"images/B3.jpg",
        name:"breakfast3",
        category:"Breakfast",
        price:"",
        description:""
    },
    {
        id:4,
        image:"images/B4.jpg",
        name:"Breakfast4",
        category:"Breakfast",
        price:"",
        description:""
    },
    {
        id:5,
        image:"images/L1.jpg",
        name:"Lunch1",
        category:"lunch",
        price:"",
        description:""
    },
    {
        id:6,
        image:"images/L2.jpg",
        name:"Lunch2",
        category:"lunch",
        price:"",
        description:""
    },
    {
        id:7,
        image:"images/L3.jpg",
        name:"Lunch3",
        category:"lunch",
        price:"",
        description:""
    },
    {
        id:8,
        image:"images/L4.jpg",
        name:"Lunch4",
        category:"lunch",
        price:"",
        description:""
    },
    {
        id:9,
        image:"images/D1.jpg",
        name:"Dinner1",
        category:"dinner",
        price:"",
        description:""
    },
    {
        id:10,
        image:"images/D2.jpg",
        name:"Dinner2",
        category:"dinner",
        price:"",
        description:""
    },
    {
        id:11,
        image:"images/D3.jpg",
        name:"Dinner3",
        category:"dinner",
        price:"",
        description:""
    },
    {
        id:12,
        image:"images/D4.jpg",
        name:"Dinner4",
        category:"dinner",
        price:"",
        description:""
    },
        
]